webapp/general/views.py
import os

from webapp.general.forms import LoginForm, RegistrationForm, ImageForm, SearchCityForm

from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app
from flask_login import current_user, login_user, logout_user
from webapp.db import db

from webapp.general.models import Auth, City, Image

from werkzeug.utils import secure_filename

blueprint = Blueprint('general', __name__, url_prefix='/general')


@blueprint.route('/', methods=['GET', 'POST'])
def index():
    title = 'Начальная страница'
    form = SearchCityForm()
    masters = None
    salons = None
    if request.method == 'POST' and form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if city:
            masters = city.masters
            salons = city.salons
        else:
            flash('По данному городу нет информации')
    return render_template('index.html', page_title=title,
                           form=form,
                           masters=masters, salons=salons)


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Авторизация'
    login_form = LoginForm()
    return render_template('login/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Auth.query.filter(Auth.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            flash('Вы успешно вошли на сайт')
            login_user(user)
            if current_user.salon:
                return redirect(url_for('salon.profile_salon'))
            elif current_user.master:
                return redirect(url_for('master.profile_master'))
            else:
                return redirect(url_for('general.index'))
    flash('Неправильная почта или пароль')
    return redirect(url_for('general.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(url_for('general.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Регистрация'
    login_form = RegistrationForm()
    return render_template('login/registration.html', page_title=title,
                           form=login_form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_register = Auth(email=form.email.data)
        new_register.set_password(form.password.data)
        db.session.add(new_register)
        db.session.commit()
        login_user(new_register)
        flash('Вы успешно зарегистрировались!')
        if form.role.data == '1':
            return redirect(url_for('user.user_reg'))
        elif form.role.data == '2':
            return redirect(url_for('master.master_reg'))
        elif form.role.data == '3':
            return redirect(url_for('salon.salon_reg'))
        return redirect(url_for('general.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('general.register'))


@blueprint.route('/save-image', methods=['POST'])
def save_image():
    form = ImageForm()
    if form.validate_on_submit():
        for image in form.image.data:
            filename = secure_filename(image.filename)
            path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            image.save(path)
            if current_user.master:
                image_for_db = Image(
                    name=filename,
                    path=path,
                    master_id=current_user.master.id
                )
            elif current_user.salon:
                image_for_db = Image(
                    name=filename,
                    path=path,
                    salon_id=current_user.salon.id
                )
            db.session.add(image_for_db)
            db.session.commit()
        if current_user.master:
            return redirect(url_for('master.profile_master'))
        elif current_user.salon:
            return redirect(url_for('salon.profile_salon'))

webapp/master/views.py
from webapp.master.forms import MasterForm
from webapp.general.forms import ImageForm

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user
from webapp.db import db

from webapp.general.models import City
from webapp.salon.models import Salon
from webapp.master.models import Master

blueprint = Blueprint('master', __name__, url_prefix='/masters')


@blueprint.route('/master-reg')
def master_reg():
    title = 'Регистрация тату-мастера'
    form = MasterForm()
    if current_user.user:
        return redirect(url_for('general.index'))
    elif current_user.master:
        return redirect(url_for('master.profile_master'))
    elif current_user.salon:
        return redirect(url_for('salon.profile_salon'))
    return render_template('login/masterreg.html', page_title=title,
                           form=form)


@blueprint.route('/process-master-reg', methods=['POST'])
def process_master_reg():
    form = MasterForm()
    if form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if not city:
            city = City(name=form.city.data)
            db.session.add(city)
            db.session.commit()

        salon = Salon.query.filter(Salon.name == form.salon.data).first()
        if not salon:
            master = Master(
                name=form.name.data,
                last_name=form.last_name.data,
                number_phone=form.number_phone.data,
                address=form.address.data,
                email=form.email.data,
                city_id=city.id,
                auth_id=current_user.id)
        else:
            master = Master(
                name=form.name.data,
                last_name=form.last_name.data,
                number_phone=form.number_phone.data,
                address=form.address.data,
                email=form.email.data,
                salon_id=salon.id,
                city_id=city.id,
                auth_id=current_user.id)

        db.session.add(master)
        db.session.commit()
        return redirect(url_for('master.profile_master'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('master.master_reg'))


@blueprint.route('/profile-master')
def profile_master():
    if not current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Профиль'
    form = ImageForm()
    images = current_user.master.images
    return render_template(
        'master/profile_master.html',
        title=title,
        form=form,
        images=images
    )


@blueprint.route('/card-master/<masterID>')
def card_master(masterID):
    master = Master.query.filter(Master.id == masterID).first()
    return render_template('master/card_master.html', master=master)

webapp/salon/views.py
from webapp.salon.forms import SalonForm
from webapp.general.forms import ImageForm

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user
from webapp.db import db

from webapp.general.models import City
from webapp.salon.models import Salon

blueprint = Blueprint('salon', __name__, url_prefix='/salons')


@blueprint.route('/salon-reg')
def salon_reg():
    form = SalonForm()
    title = 'Регистрация Салона'
    if current_user.user:
        return redirect(url_for('general.index'))
    elif current_user.master:
        return redirect(url_for('master.profile_master'))
    elif current_user.salon:
        return redirect(url_for('salon.profile_salon'))
    return render_template('login/salonreg.html', page_title=title,
                           form=form)


@blueprint.route('/process-salon-reg', methods=['POST'])
def process_salon_reg():
    form = SalonForm()
    if form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if not city:
            city = City(name=form.city.data)
            db.session.add(city)
            db.session.commit()

        new_salon = Salon(
            name=form.name.data,
            number_phone=form.number_phone.data,
            address=form.address.data,
            email=form.email.data,
            city_id=city.id,
            auth_id=current_user.id)

        db.session.add(new_salon)
        db.session.commit()
        return redirect(url_for('salon.profile_salon'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('general.salon_reg'))


@blueprint.route('/profile-salon')
def profile_salon():
    if not current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Профиль'
    form = ImageForm()
    images = current_user.salon.images
    return render_template('salon/profile_salon.html', title=title, form=form, images=images)


@blueprint.route('/card-salon/<salonID>')
def card_salon(salonID):
    salon = Salon.query.filter(Salon.id == salonID).first()
    return render_template('salon/card_salon.html', salon=salon)

webapp/user/views.py
from webapp.user.forms import UserForm

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user
from webapp.db import db

from webapp.general.models import City
from .models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/user-reg')
def user_reg():
    form = UserForm()
    title = 'Регистрация пользователя'
    if current_user.user:
        return redirect(url_for('general.index'))
    elif current_user.master:
        return redirect(url_for('master.profile_master'))
    elif current_user.salon:
        return redirect(url_for('salon.profile_salon'))
    return render_template('login/userreg.html', page_title=title,
                           form=form)


@blueprint.route('/process-user-reg', methods=['POST'])
def process_user_reg():
    form = UserForm()
    if form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if not city:
            city = City(name=form.city.data)
            db.session.add(city)
            db.session.commit()

        new_user = User(
            name=form.name.data,
            last_name=form.last_name.data,
            number_phone=form.number_phone.data,
            email=form.email.data,
            date_of_birth=form.date_of_birth.data,
            city_id=city.id,
            auth_id=current_user.id)

        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('general.index'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('user.user_reg'))


# @blueprint.route('/profile-user')
# def profile_user():
#     return render_template('profile_user.html')

webapp/templates/login/login.html
{% extends "base.html" %}
{% block content %}
    <body class='backlogin'>
    <div class='container'>
        <div class="row align-items-center">
            {% include('flash_massages.html') %}
            <span
                class="border border-1 col-3 bg-light text-dark rounded-3 shadow-lg p-3 mb-5 rounded position-absolute top-50 start-50 translate-middle">
                <h1>{{ page_title }}</h1>
                <form action="{{ url_for('general.process_login') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.email.label }}
                        {{ form.email() }}
                    </div>
                    <div class="mb-3">
                        {{ form.password.label }}
                        {{ form.password() }}
                    </div>
                    {{ form.submit }}
                    <br>
                </form>
            </span>
        </div>
    </div>
    </body>
{% endblock %}

webapp/templates/login/masterreg.html
{% extends "base.html" %}
{% block content %}
<body class='backmasreg'>
    <div class='container'>
        <div class="row align-items-center">
            {% include('flash_massages.html') %}
            <div class='col'></div>
            <span
                class="border border-1 col-3 bg-light text-dark rounded-3 shadow-lg p-3 mb-5 rounded position-absolute top-50 start-50 translate-middle">
                <h1>{{ page_title }}</h1>
                <form action="{{ url_for('master.process_master_reg') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.name.label }}
                        {{ form.name() }}
                    </div>
                    <div class="mb-3">
                        {{ form.last_name.label }}
                        {{ form.last_name() }}
                    </div>
                    <div class="mb-3">
                        {{ form.address.label }}
                        {{ form.address() }}
                    </div>
                    <div class="mb-3">
                        {{ form.number_phone.label }}
                        {{ form.number_phone() }}
                    </div>
                    <div class="mb-3">
                        {{ form.email.label }}
                        {{ form.email() }}
                    </div>
                    <div class="mb-3">
                        {{ form.salon.label }}
                        {{ form.salon() }}
                    </div>
                    <div class="mb-3">
                        {{ form.city.label }}
                        {{ form.city() }}
                    </div>
                    <br>
                    {{ form.submit }}
                </form>
            </span>
            <div class="col"></div>
        </div>
    </div>
</body>
{% endblock %}

webapp/templates/login/registration.html
{% extends "base.html" %}
{% block content %}
<body class='backreg'>
    <div class='container'>
        <div class="row align-items-center">
            {% include('flash_massages.html') %}
            <div class='col'></div>
            <span
                class="border border-1 col-3 bg-light text-dark rounded-3 shadow-lg p-3 mb-5 rounded position-absolute top-50 start-50 translate-middle">
                <h1>{{ page_title }}</h1>
                <form action="{{ url_for('general.process_reg') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.email.label }}
                        {{ form.email() }}
                    </div>
                    <div class="mb-3">
                        {{ form.password.label }}
                        {{ form.password() }}
                    </div>
                    <div class="mb-3">
                        {{ form.password2.label }}
                        {{ form.password2() }}
                    </div>
                    <div class="form-check form-check-inline">
                        <h5>{{ form.role.label }}</h5>
                        {{ form.role() }}
                    </div>
                    <br>
                    {{ form.submit }}
                    <br>
                </form>
            </span>
            <div class="col"></div>
        </div>
    </div>
</body>
{% endblock %}

webapp/templates/login/salonreg.html
{% extends "base.html" %}
{% block content %}
<body class="backsalreg">
    <div class='container'>
        <div class="row align-items-center">
            {% include('flash_massages.html') %}
            <div class='col'></div>
            <span
                class="border border-1 col-3 bg-light text-dark rounded-3 shadow-lg p-3 mb-5 rounded position-absolute top-50 start-50 translate-middle">
                <h1>{{ page_title }}</h1>
                <form action="{{ url_for('salon.process_salon_reg') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.name.label }}
                        {{ form.name() }}
                    </div>
                    <div class="mb-3">
                        {{ form.number_phone.label }}
                        {{ form.number_phone() }}
                    </div>
                    <div class="mb-3">
                        {{ form.address.label }}
                        {{ form.address() }}
                    </div>
                    <div class="mb-3">
                        {{ form.email.label }}
                        {{ form.email() }}
                    </div>
                    <div class="mb-3">
                        {{ form.city.label }}
                        {{ form.city() }}
                    </div>
                    <br>
                    {{ form.submit }}
                </form>
            </span>
            <div class="col"></div>
        </div>
    </div>
</body>
{% endblock %}

webapp/templates/login/userreg.html
{% extends "base.html" %}
{% block content %}
<body class='backusreg'>
    <div class='container'>
        <div class="row align-items-center">
            {% include('flash_massages.html') %}
            <div class='col'></div>
            <span
                class="border border-1 col-3 bg-light text-dark rounded-3 shadow-lg p-3 mb-5 rounded position-absolute top-50 start-50 translate-middle">
                <h1>{{ page_title }}</h1>
                <form action="{{ url_for('user.process_user_reg') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.name.label }}
                        {{ form.name() }}
                    </div>
                    <div class="mb-3">
                        {{ form.last_name.label }}
                        {{ form.last_name() }}
                    </div>
                    <div class="mb-3">
                        {{ form.number_phone.label }}
                        {{ form.number_phone() }}
                    </div>
                    <div class="mb-3">
                        {{ form.date_of_birth.label }}
                        {{ form.date_of_birth() }}
                    </div>
                    <div class="mb-3">
                        {{ form.email.label }}
                        {{ form.email() }}
                    </div>
                    <div class="mb-3">
                        {{ form.city.label }}
                        {{ form.city() }}
                    </div>
                    <br>
                    {{ form.submit }}
                </form>
            </span>
            <div class="col"></div>
        </div>
    </div>
</body>
{% endblock %}