webapp/salon/models.py
from webapp.db import db


class Salon(db.Model):
    __tablename__ = 'salon'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    number_phone = db.Column(db.String, nullable=False, unique=True)
    address = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False, unique=True)

    city_id = db.Column(db.Integer, db.ForeignKey('city.id'), nullable=False)
    city = db.relationship('City', backref='salons')

    auth_id = db.Column(db.Integer, db.ForeignKey('auth.id'))
    auth = db.relationship('Auth', backref=db.backref('salon', uselist=False))

    def __repr__(self):
        return f'''<Tattoo Salon {self.name}, {self.address}, {self.email},
                    {self.number_phone}, {self.city_id}, {self.city}>'''

webapp/user/models.py
from webapp.db import db


class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    last_name = db.Column(db.String, nullable=False)
    number_phone = db.Column(db.String, nullable=False, unique=True)
    email = db.Column(db.String, nullable=False, unique=True)
    date_of_birth = db.Column(db.Date, nullable=False)

    city_id = db.Column(db.Integer, db.ForeignKey('city.id'), nullable=False)
    city = db.relationship('City', backref='users')

    auth_id = db.Column(db.Integer, db.ForeignKey('auth.id'))
    auth = db.relationship('Auth', backref=db.backref('user', uselist=False))

    def __repr__(self):
        return f'''<User {self.name}, {self.last_name}, {self.email},
                    {self.number_phone}>'''

webapp/salon/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.fields.html5 import EmailField
from wtforms.validators import InputRequired, ValidationError
from .models import Salon


class SalonForm(FlaskForm):
    name = StringField('Название Салона', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    number_phone = StringField('Номер телефона',
                               validators=[InputRequired()],
                               render_kw={"class": "form-control"})
    address = StringField('Адресс салона',
                          validators=[InputRequired()],
                          render_kw={"class": "form-control"})
    email = EmailField('Электронная почта', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    city = StringField('Город', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    submit = SubmitField(
        'Зарегистрироваться',
        render_kw={"class": "btn btn-primary"}
    )

    def validate_number_phone(self, number_phone):
        count_phone = Salon.query.filter_by(number_phone=number_phone.data).count()
        if count_phone > 0:
            raise ValidationError('Такой номер телефона уже используется')
    
    def validate_email(self, email):
        count_email = Salon.query.filter_by(email=email.data).count()
        if count_email > 0:
            raise ValidationError('Такой почтовый адрес уже существует')

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.fields.html5 import EmailField, DateField
from wtforms.validators import InputRequired, ValidationError
from .models import User


class UserForm(FlaskForm):
    name = StringField('Имя', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    last_name = StringField('Фамилия', validators=[InputRequired()],
                            render_kw={"class": "form-control"})
    number_phone = StringField('Номер телефона',
                               validators=[InputRequired()],
                               render_kw={"class": "form-control"})
    email = EmailField('Электронная почта', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    date_of_birth = DateField('Введите дату рождения',
                              validators=[InputRequired()],
                              format='%Y-%m-%d',
                              render_kw={"class": "form-control"})
    city = StringField('Город', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    submit = SubmitField(
        'Зарегистрироваться',
        render_kw={"class": "btn btn-primary"}
    )

    def validate_number_phone(self, number_phone):
        count_number_phone = User.query.filter_by(number_phone=number_phone.data).count()
        if count_number_phone > 0:
            raise ValidationError('Такой номер уже используется')

    def validate_email(self, email):
        count_email = User.query.filter_by(email=email.data).count()
        if count_email > 0:
            raise ValidationError('Такой почтовый адрес уже существует')

webapp/general/views.py
import os

from webapp.general.forms import LoginForm, RegistrationForm, ImageForm, SearchCityForm

from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app
from flask_login import current_user, login_user, logout_user
from webapp.db import db

from webapp.general.models import Auth, City, Image

from werkzeug.utils import secure_filename

blueprint = Blueprint('general', __name__, url_prefix='/general')


@blueprint.route('/', methods=['GET', 'POST'])
def index():
    title = 'Начальная страница'
    form = SearchCityForm()
    masters = None
    salons = None
    if request.method == 'POST' and form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if city:
            masters = city.masters
            salons = city.salons
        else:
            flash('По данному городу нет информации')
    return render_template('index.html', page_title=title,
                           form=form,
                           masters=masters, salons=salons)


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Авторизация'
    login_form = LoginForm()
    return render_template('login/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Auth.query.filter(Auth.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            flash('Вы успешно вошли на сайт')
            login_user(user)
            if current_user.salon:
                return redirect(url_for('salon.profile_salon'))
            elif current_user.master:
                return redirect(url_for('master.profile_master'))
            else:
                return redirect(url_for('general.index'))
    flash('Неправильная почта или пароль')
    return redirect(url_for('general.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(url_for('general.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Регистрация'
    login_form = RegistrationForm()
    return render_template('login/registration.html', page_title=title,
                           form=login_form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_register = Auth(email=form.email.data)
        new_register.set_password(form.password.data)
        db.session.add(new_register)
        db.session.commit()
        login_user(new_register)
        flash('Вы успешно зарегистрировались!')
        if form.role.data == '1':
            return redirect(url_for('user.user_reg'))
        elif form.role.data == '2':
            return redirect(url_for('master.master_reg'))
        elif form.role.data == '3':
            return redirect(url_for('salon.salon_reg'))
        return redirect(url_for('general.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('general.register'))


@blueprint.route('/save-image', methods=['POST'])
def save_image():
    form = ImageForm()
    if form.validate_on_submit():
        for image in form.image.data:
            filename = secure_filename(image.filename)
            path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            image.save(path)
            if current_user.master:
                image_for_db = Image(
                    name=filename,
                    path=path,
                    master_id=current_user.master.id
                )
            elif current_user.salon:
                image_for_db = Image(
                    name=filename,
                    path=path,
                    salon_id=current_user.salon.id
                )
            db.session.add(image_for_db)
            db.session.commit()
        if current_user.master:
            return redirect(url_for('master.profile_master'))
        elif current_user.salon:
            return redirect(url_for('salon.profile_salon'))

webapp/master/views.py
from webapp.master.forms import MasterForm
from webapp.general.forms import ImageForm

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user
from webapp.db import db

from webapp.general.models import City
from webapp.salon.models import Salon
from webapp.master.models import Master

blueprint = Blueprint('master', __name__, url_prefix='/masters')


@blueprint.route('/master-reg')
def master_reg():
    title = 'Регистрация тату-мастера'
    form = MasterForm()
    if current_user.user:
        return redirect(url_for('general.index'))
    elif current_user.master:
        return redirect(url_for('master.profile_master'))
    elif current_user.salon:
        return redirect(url_for('salon.profile_salon'))
    return render_template('login/masterreg.html', page_title=title,
                           form=form)


@blueprint.route('/process-master-reg', methods=['POST'])
def process_master_reg():
    form = MasterForm()
    if form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if not city:
            city = City(name=form.city.data)
            db.session.add(city)
            db.session.commit()

        salon = Salon.query.filter(Salon.name == form.salon.data).first()
        if not salon:
            master = Master(
                name=form.name.data,
                last_name=form.last_name.data,
                number_phone=form.number_phone.data,
                address=form.address.data,
                email=form.email.data,
                city_id=city.id,
                auth_id=current_user.id)
        else:
            master = Master(
                name=form.name.data,
                last_name=form.last_name.data,
                number_phone=form.number_phone.data,
                address=form.address.data,
                email=form.email.data,
                salon_id=salon.id,
                city_id=city.id,
                auth_id=current_user.id)

        db.session.add(master)
        db.session.commit()
        return redirect(url_for('master.profile_master'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('master.master_reg'))


@blueprint.route('/profile-master')
def profile_master():
    if not current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Профиль'
    form = ImageForm()
    images = current_user.master.images
    return render_template(
        'master/profile_master.html',
        title=title,
        form=form,
        images=images
    )


@blueprint.route('/card-master/<masterID>')
def card_master(masterID):
    master = Master.query.filter(Master.id == masterID).first()
    return render_template('master/card_master.html', master=master)

webapp/salon/views.py
from webapp.salon.forms import SalonForm
from webapp.general.forms import ImageForm

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user
from webapp.db import db

from webapp.general.models import City
from webapp.salon.models import Salon

blueprint = Blueprint('salon', __name__, url_prefix='/salons')


@blueprint.route('/salon-reg')
def salon_reg():
    form = SalonForm()
    title = 'Регистрация Салона'
    if current_user.user:
        return redirect(url_for('general.index'))
    elif current_user.master:
        return redirect(url_for('master.profile_master'))
    elif current_user.salon:
        return redirect(url_for('salon.profile_salon'))
    return render_template('login/salonreg.html', page_title=title,
                           form=form)


@blueprint.route('/process-salon-reg', methods=['POST'])
def process_salon_reg():
    form = SalonForm()
    if form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if not city:
            city = City(name=form.city.data)
            db.session.add(city)
            db.session.commit()

        new_salon = Salon(
            name=form.name.data,
            number_phone=form.number_phone.data,
            address=form.address.data,
            email=form.email.data,
            city_id=city.id,
            auth_id=current_user.id)

        db.session.add(new_salon)
        db.session.commit()
        return redirect(url_for('salon.profile_salon'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('general.salon_reg'))


@blueprint.route('/profile-salon')
def profile_salon():
    if not current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Профиль'
    form = ImageForm()
    images = current_user.salon.images
    return render_template('salon/profile_salon.html', title=title, form=form, images=images)


@blueprint.route('/card-salon/<salonID>')
def card_salon(salonID):
    salon = Salon.query.filter(Salon.id == salonID).first()
    return render_template('salon/card_salon.html', salon=salon)

webapp/user/views.py
from webapp.user.forms import UserForm

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user
from webapp.db import db

from webapp.general.models import City
from .models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/user-reg')
def user_reg():
    form = UserForm()
    title = 'Регистрация пользователя'
    if current_user.user:
        return redirect(url_for('general.index'))
    elif current_user.master:
        return redirect(url_for('master.profile_master'))
    elif current_user.salon:
        return redirect(url_for('salon.profile_salon'))
    return render_template('login/userreg.html', page_title=title,
                           form=form)


@blueprint.route('/process-user-reg', methods=['POST'])
def process_user_reg():
    form = UserForm()
    if form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if not city:
            city = City(name=form.city.data)
            db.session.add(city)
            db.session.commit()

        new_user = User(
            name=form.name.data,
            last_name=form.last_name.data,
            number_phone=form.number_phone.data,
            email=form.email.data,
            date_of_birth=form.date_of_birth.data,
            city_id=city.id,
            auth_id=current_user.id)

        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('general.index'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('user.user_reg'))


# @blueprint.route('/profile-user')
# def profile_user():
#     return render_template('profile_user.html')

webapp/templates/base.html
<!doctype html>
<html lang="ru" style='width:100%; height:100%'>


<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <style>
            body {
                background: #466368;
                background-attachment: fixed;
                background: linear-gradient(#648880, #293f50);
                }
            .backlogin {
                background: url('/static/background/background1.jpg');
                background-attachment: fixed;
                color: rgb(0, 0, 0);
                }
            .backreg {
                background: url('/static/background/background2.jpg');
                background-attachment: fixed;
                color: rgb(0, 0, 0);
                }
            .backmasreg {
                background: url('/static/background/background3.jpg');
                background-attachment: fixed;
                color: rgb(0, 0, 0);
                }
            .backusreg {
                background: url('/static/background/background4.jpg');
                background-attachment: fixed;
                color: rgb(0, 0, 0);
                }
            .backsalreg {
                background: url('/static/background/background5.jpg');
                background-attachment: fixed;
                color: rgb(0, 0, 0);
                }
            .inf-content {
                border:1px solid #DDDDDD;
                -webkit-border-radius:10px;
                -moz-border-radius:10px;
                border-radius:10px;
                box-shadow: 7px 7px 7px rgba(0, 0, 0, 0.3);
                }
            
        </style>
    <title>{{ page_title }}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('general.index') }}">Tattoo</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('general.index') }}">Главная</a>
                    </li>
                    {% if current_user.master %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('master.profile_master') }}">Профиль</a>
                    </li>
                    {% elif current_user.salon %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('salon.profile_salon') }}">Профиль</a>
                    </li>
                    {% endif %}
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('general.logout') }}">Выйти</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('general.register') }}">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('general.login') }}">Войти</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    
        {% block content %}{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
        -->
</body>

</html>

webapp/templates/flash_massages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning" role="alert">
            {{ message }}<br>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

webapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
    sizefont { font-size:25px; }
</style>
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-warning" role="alert">
            {% for message in messages %}
            {{ message }}<br>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
    </div>
    <br>

    <form class="container" action="" method="post">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.city() }}
        </div>
        {{ form.submit() }}
    </form>
    <br>


    <div class="row">
        <dt class="col-sm-6">
            <h2 align="center">Салоны</h2>

            <dl class="row">
                {% if salons %}
                {% for salon in salons %}
                <sizefont><a href="{{ url_for('salon.card_salon', salonID = salon.id) }}">{{ salon.name }}</a></sizefont>
                {% endfor %}
                {% endif %}
            </dl>
        </dt>

        <dt class="col-sm-6">
            <h2 align="center">Мастера</h2>

            <dl class="row">
                {% if masters %}
                {% for master in masters %}
                <sizefont><a href="{{ url_for('master.card_master', masterID = master.id) }}">{{ master.name }} {{master.last_name}}</a></sizefont>
                {% endfor %}
                {% endif %}
            </dl>
        </dt>
    </div>
{% endblock %}

webapp/templates/salon.html
<!doctype html>
<html lang="ru">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

        <title>{{ page_title }}</title>
    </head>
    <body>
        <div class='container'>
            <div class="row align-items-center">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-warning" role="alert">
                        {% for message in messages %}
                            {{ message }}<br>
                        {% endfor %}
                        </div>
                    {% endif %}
                {% endwith %}
            <div class='col'></div>
            <div class="col">
                <h1>{{ page_title }}</h1>
                <form action="{{ url_for('login') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.name.label }}
                        {{ form.name() }}
                    </div>
                    <div class="mb-3">
                        {{ form.number_phone.label }}
                        {{ form.number_phone() }}
                    </div>
                    <div class="mb-3">
                        {{ form.address.label }}
                        {{ form.address() }}
                    </div>
                    <div class="mb-3">
                        {{ form.city.label }}
                        {{ form.city() }}
                    </div>
                    <br>
                    {{ form.submit }}
                </form>
            </div>
            <div class="col"></div>
            </div>
        </div>

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
        -->
    </body>
</html>

webapp/templates/user.html
<!doctype html>
<html lang="ru">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

        <title>{{ page_title }}</title>
    </head>
    <body>
        <div class='container'>
            <div class="row align-items-center">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-warning" role="alert">
                        {% for message in messages %}
                            {{ message }}<br>
                        {% endfor %}
                        </div>
                    {% endif %}
                {% endwith %}
            <div class='col'></div>
            <div class="col">
                <h1>{{ page_title }}</h1>
                <form action="{{ url_for('login') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.name.label }}
                        {{ form.name() }}
                    </div>
                    <div class="mb-3">
                        {{ form.last_name.label }}
                        {{ form.last_name() }}
                    </div>
                    <div class="mb-3">
                        {{ form.number_phone.label }}
                        {{ form.number_phone() }}
                    </div>
                    <div class="mb-3">
                        {{ form.date_of_birth.label }}
                        {{ form.date_of_birth() }}
                    </div>
                    <div class="mb-3">
                        {{ form.city.label }}
                        {{ form.city() }}
                    </div>
                    <br>
                    {{ form.submit }}
                </form>
            </div>
            <div class="col"></div>
            </div>
        </div>

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
        -->
    </body>
</html>