webapp/salon/models.py
from webapp.db import db


class Salon(db.Model):
    __tablename__ = 'salon'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    number_phone = db.Column(db.String, nullable=False, unique=True)
    address = db.Column(db.String, nullable=False)
    email = db.Column(db.String, nullable=False, unique=True)

    city_id = db.Column(db.Integer, db.ForeignKey('city.id'), nullable=False)
    city = db.relationship('City', backref='salons')

    auth_id = db.Column(db.Integer, db.ForeignKey('auth.id'))
    auth = db.relationship('Auth', backref=db.backref('salon', uselist=False))

    def __repr__(self):
        return f'''<Tattoo Salon {self.name}, {self.address}, {self.email},
                    {self.number_phone}, {self.city_id}, {self.city}>'''

webapp/salon/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.fields.html5 import EmailField
from wtforms.validators import InputRequired, ValidationError
from .models import Salon


class SalonForm(FlaskForm):
    name = StringField('Название Салона', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    number_phone = StringField('Номер телефона',
                               validators=[InputRequired()],
                               render_kw={"class": "form-control"})
    address = StringField('Адресс салона',
                          validators=[InputRequired()],
                          render_kw={"class": "form-control"})
    email = EmailField('Электронная почта', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    city = StringField('Город', validators=[InputRequired()],
                       render_kw={"class": "form-control"})
    submit = SubmitField(
        'Зарегистрироваться',
        render_kw={"class": "btn btn-primary"}
    )

    def validate_number_phone(self, number_phone):
        count_phone = Salon.query.filter_by(number_phone=number_phone.data).count()
        if count_phone > 0:
            raise ValidationError('Такой номер телефона уже используется')
    
    def validate_email(self, email):
        count_email = Salon.query.filter_by(email=email.data).count()
        if count_email > 0:
            raise ValidationError('Такой почтовый адрес уже существует')

webapp/general/views.py
import os

from webapp.general.forms import LoginForm, RegistrationForm, ImageForm, SearchCityForm

from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app
from flask_login import current_user, login_user, logout_user
from webapp.db import db

from webapp.general.models import Auth, City, Image

from werkzeug.utils import secure_filename

blueprint = Blueprint('general', __name__, url_prefix='/general')


@blueprint.route('/', methods=['GET', 'POST'])
def index():
    title = 'Начальная страница'
    form = SearchCityForm()
    masters = None
    salons = None
    if request.method == 'POST' and form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if city:
            masters = city.masters
            salons = city.salons
        else:
            flash('По данному городу нет информации')
    return render_template('index.html', page_title=title,
                           form=form,
                           masters=masters, salons=salons)


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Авторизация'
    login_form = LoginForm()
    return render_template('login/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Auth.query.filter(Auth.email == form.email.data).first()
        if user and user.check_password(form.password.data):
            flash('Вы успешно вошли на сайт')
            login_user(user)
            if current_user.salon:
                return redirect(url_for('salon.profile_salon'))
            elif current_user.master:
                return redirect(url_for('master.profile_master'))
            else:
                return redirect(url_for('general.index'))
    flash('Неправильная почта или пароль')
    return redirect(url_for('general.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(url_for('general.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Регистрация'
    login_form = RegistrationForm()
    return render_template('login/registration.html', page_title=title,
                           form=login_form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_register = Auth(email=form.email.data)
        new_register.set_password(form.password.data)
        db.session.add(new_register)
        db.session.commit()
        login_user(new_register)
        flash('Вы успешно зарегистрировались!')
        if form.role.data == '1':
            return redirect(url_for('user.user_reg'))
        elif form.role.data == '2':
            return redirect(url_for('master.master_reg'))
        elif form.role.data == '3':
            return redirect(url_for('salon.salon_reg'))
        return redirect(url_for('general.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('general.register'))


@blueprint.route('/save-image', methods=['POST'])
def save_image():
    form = ImageForm()
    if form.validate_on_submit():
        for image in form.image.data:
            filename = secure_filename(image.filename)
            path = os.path.join(current_app.config['UPLOAD_FOLDER'], filename)
            image.save(path)
            if current_user.master:
                image_for_db = Image(
                    name=filename,
                    path=path,
                    master_id=current_user.master.id
                )
            elif current_user.salon:
                image_for_db = Image(
                    name=filename,
                    path=path,
                    salon_id=current_user.salon.id
                )
            db.session.add(image_for_db)
            db.session.commit()
        if current_user.master:
            return redirect(url_for('master.profile_master'))
        elif current_user.salon:
            return redirect(url_for('salon.profile_salon'))

webapp/salon/views.py
from webapp.salon.forms import SalonForm
from webapp.general.forms import ImageForm

from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user
from webapp.db import db

from webapp.general.models import City
from webapp.salon.models import Salon

blueprint = Blueprint('salon', __name__, url_prefix='/salons')


@blueprint.route('/salon-reg')
def salon_reg():
    form = SalonForm()
    title = 'Регистрация Салона'
    if current_user.user:
        return redirect(url_for('general.index'))
    elif current_user.master:
        return redirect(url_for('master.profile_master'))
    elif current_user.salon:
        return redirect(url_for('salon.profile_salon'))
    return render_template('login/salonreg.html', page_title=title,
                           form=form)


@blueprint.route('/process-salon-reg', methods=['POST'])
def process_salon_reg():
    form = SalonForm()
    if form.validate_on_submit():
        city = City.query.filter(City.name == form.city.data).first()
        if not city:
            city = City(name=form.city.data)
            db.session.add(city)
            db.session.commit()

        new_salon = Salon(
            name=form.name.data,
            number_phone=form.number_phone.data,
            address=form.address.data,
            email=form.email.data,
            city_id=city.id,
            auth_id=current_user.id)

        db.session.add(new_salon)
        db.session.commit()
        return redirect(url_for('salon.profile_salon'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Ошибка в поле "{getattr(form, field).label.text}": {error}')
        return redirect(url_for('general.salon_reg'))


@blueprint.route('/profile-salon')
def profile_salon():
    if not current_user.is_authenticated:
        return redirect(url_for('general.index'))
    title = 'Профиль'
    form = ImageForm()
    images = current_user.salon.images
    return render_template('salon/profile_salon.html', title=title, form=form, images=images)


@blueprint.route('/card-salon/<salonID>')
def card_salon(salonID):
    salon = Salon.query.filter(Salon.id == salonID).first()
    return render_template('salon/card_salon.html', salon=salon)

webapp/templates/salon/card_salon.html
{% extends "base.html" %}
{% block content %}
    <div class="container bootstrap snippets bootdey">
        <div class="panel-body inf-content">
            <div class="row">
                <div class="col-md-4">
                    <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip"
                        src="https://bootdey.com/img/Content/avatar/avatar7.png" data-original-title="Usuario">
                </div>
                <div class="col-md-6">
                    <strong><h3>Информация о салоне</h3></strong><br><br>
                    <div class="table-responsive">
                        <table class="table table-user-information">
                            <tbody>

                                <tr>
                                    <td>
                                        <strong>
                                            <span class="glyphicon glyphicon-user  text-primary"></span>
                                            Название салона
                                        </strong>
                                    </td>
                                    <td class="text-primary">
                                        {{ salon.name }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <strong>
                                            <span class="glyphicon glyphicon-eye-open text-primary"></span>
                                            Адрес
                                        </strong>
                                    </td>
                                    <td class="text-primary">
                                        {{ salon.address }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <strong>
                                            <span class="glyphicon glyphicon-envelope text-primary"></span>
                                            Номер телефона
                                        </strong>
                                    </td>
                                    <td class="text-primary">
                                        {{ salon.number_phone }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <strong>
                                            <span class="glyphicon glyphicon-calendar text-primary"></span>
                                            Электронная почта
                                        </strong>
                                    </td>
                                    <td class="text-primary">
                                        {{ salon.email }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webapp/templates/salon/profile_salon.html
{% extends "base.html" %}
{% block content %}
    <div class='container'>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-warning" role="alert">
            {% for message in messages %}
            {{ message }}<br>
            {% endfor %}
        </div>
        {% endif %}
        {% endwith %}
        <dl class="row">
            <dt class="col-sm-3">Название Салона</dt>
            <dd class="col-sm-9">{{ current_user.salon.name }}</dd>

            <dt class="col-sm-3">Адрес</dt>
            <dd class="col-sm-9">{{ current_user.salon.address }}</dd>

            <dt class="col-sm-3">Электронная почта</dt>
            <dd class="col-sm-9">{{ current_user.salon.email }}</dd>

            <dt class="col-sm-3 text-truncate">Номер телефона</dt>
            <dd class="col-sm-9">{{ current_user.salon.number_phone }}</dd>

            <dt class="col-sm-12">
                <h2 align="center">Эскизы</h2>
                <form action="{{ url_for('general.save_image') }}" method="post" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.image() }}
                    </div>
                    {{ form.submit }}
                </form>
                <dl class="row">
                    {% if images %}
                    {% for image in images %}
                    <dt class="col-sm-4">
                        <label class="form-label">{{ image.name }}</label><br>

                        <a href='big.jpg' target='_blank'>
                            <img src='/static/images/{{ image.name }}' alt="{{ image.name }}"
                                class="rounded mx-auto d-block" width="200" height="200">
                        </a>

                        <br>
                    </dt>
                    {% endfor %}
                    {% endif %}
                </dl>
            </dt>
        </dl>
    </div>
{% endblock %}